[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "px"
version = "0.0.1"
dependencies =[
'Pillow', 'numpy', 'scikit-learn'  
]

[project.scripts]
px = "px.main:main"